import Head from "next/head";

type Props = {
  title?: string;
  children: React.ReactNode;
};

const Container = (props: Props) => {
  const { children, ...customMeta } = props;

  const meta = {
    title: "Next.js with Zustand",
    ...customMeta,
  };

  return (
    <>
      <Head>
        <title>{meta.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
};

export default Container;
